export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST "
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS "
export const CREATE_USER_FAIL = "CREATE_USER_FAIL "
export const CREATE_USER_RESET = "CREATE_USER_RESET "

export  const LOGOUT_USER = "LOGOUT_USER"

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST "
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS "
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL "
export const LOGIN_USER_RESET = "LOGIN_USER_RESET "

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const GET_USER_RESET = "GET_USER_RESET";